---
title: "IST 400/600: Open Source Software Development Practicum"
subtitle: "Syracuse University, Fall 2026"
toc: true
---

## Course info

**Room:** Hinds Hall 117

**Time:** Thursdays, 2:00PM -- 4:45PM

**Instructor:** Collin Capano

**Email:** cdcapano@syr.edu

**Office hours:** Wednesdays, 2:00PM -- 3:00PM in Hinds 206A, or by appointment.

**[Syllabus](syllabus.qmd)**


## Class Schedule

*Note:* schedule subject to change as we progress through the semester.

| Week | Dates | Topic |
|----|--------------|----------------------|
| 1  | 8/27  | Intro; project selection |
| 2  | 9/3   | Creating and managing environments |
| 3  | 9/10  | Git 1: Branches and merge conflicts |
| 4  | 9/17  | Git 2: Collaborating on GitHub |
| 5  | 9/24  | Anatomy of a software package |
| 6  | 10/1  | Effective use of AI |
| 7  | 10/8  | Development day |
| 8  | 10/15 | Writing and deploying CI tests via GitHub actions |
| 9  | 10/22 | Creating a documentation page via GitHub pages |
| 10 | 10/29 | Choosing an open source license |
| 11 | 11/5  | Packaging and deployment |
| 12 | 11/12 | Development models / writing a contributing guide |
| 13 | 11/19 | Development day |
| 14 | 11/26 | Thanksgiving - no class |
| 15 | 12/3  | Project presentations |
| -- | 12/10 | Grad students: project papers due |


## Important dates

| Date        | |
|-------------|---------------------------------------------------|
| 8/24 | First day of classes |
| 9/14 | Academic/Financial drop deadline; Religious observance notification deadline |
| 10/12 - 10/13 | Fall break |
| 11/20 | Withdrawal deadline |
| 11/22 - 11/29 | Thanksgiving Break |
| 12/8 | Last day of classes |
