---
title: "1. Project management"
order: 1
---

## Lecture - 9/2/26

In the first part I review what you should discuss and establish with your
mentor the first time you meet with them. I then do a brief review of
package and environment managers.

### Recording

<iframe id="kmsembed-1_32ad4iiy" width="640" height="360" src="https://video.syr.edu/embed/secure/iframe/entryId/1_32ad4iiy/uiConfId/45992161/st/0" class="kmsembed" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" referrerPolicy="no-referrer-when-downgrade" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="IST 400/600 Lecture 9-2-26"></iframe>

### Slides

[download PDF](project_management.pdf)

<object data="project_management.pdf" type="application/pdf" width="100%" height="600" style="border: 1px solid #ccc;">
Your browser cannot display PDFs inline. <a href="project_management.pdf">Download the slides</a> instead.
</object>

## Conda info

As stated in the lecture, here are the instructions for installing Miniconda:

- [Install Miniconda](conda_install.qmd)

Here is a tutorial that goes into more details about what an environment is,
and how to use conda on the command line:

- [Bash variables, environments, and `conda`](conda.qmd)
